# Custom Env Variables
export EDITOR="nvim"
export ANDROID_HOME="/home/$USER/.android/android-sdk" # Android-Studio
export CHROME_EXECUTABLE="/usr/bin/chromium"  # Android-Studio
export PATH="/opt/flutter/bin:$PATH"  # Android-Studio

# Aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ls="exa --icons"
alias sshpi="ssh smj@192.168.1.120"
alias vim="nvim"
